"""Add ML features and index to StreetlightLog

Revision ID: 0be2a3a925d1
Revises: 7edbdd870594
Create Date: 2026-05-07 09:45:09.025917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be2a3a925d1'
down_revision: Union[str, Sequence[str], None] = '7edbdd870594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streetlight_logs', sa.Column('d_voltage', sa.Float(), nullable=True))
    op.add_column('streetlight_logs', sa.Column('d_current', sa.Float(), nullable=True))
    op.add_column('streetlight_logs', sa.Column('d_power', sa.Float(), nullable=True))
    op.add_column('streetlight_logs', sa.Column('std_voltage_5', sa.Float(), nullable=True))
    op.add_column('streetlight_logs', sa.Column('std_current_5', sa.Float(), nullable=True))
    op.create_index(op.f('ix_streetlight_logs_streetlight_id'), 'streetlight_logs', ['streetlight_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streetlight_logs_streetlight_id'), table_name='streetlight_logs')
    op.drop_column('streetlight_logs', 'std_current_5')
    op.drop_column('streetlight_logs', 'std_voltage_5')
    op.drop_column('streetlight_logs', 'd_power')
    op.drop_column('streetlight_logs', 'd_current')
    op.drop_column('streetlight_logs', 'd_voltage')
    # ### end Alembic commands ###
