"""add fault_type to streetlight_log

Revision ID: 1d8e341dd3cc
Revises: de27994391e7
Create Date: 2026-05-09 00:29:52.187058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8e341dd3cc'
down_revision: Union[str, Sequence[str], None] = 'de27994391e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streetlight_logs', sa.Column('fault_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streetlight_logs', 'fault_type')
    # ### end Alembic commands ###
