"""add advanced telemetry fields

Revision ID: 7edbdd870594
Revises: 59fdaf7e2466
Create Date: 2026-04-24 19:01:08.675678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7edbdd870594'
down_revision: Union[str, Sequence[str], None] = '59fdaf7e2466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streetlight_logs', sa.Column('operating_hours', sa.Float(), nullable=True))
    op.add_column('streetlight_logs', sa.Column('voltage_fluctuation', sa.Float(), nullable=True))
    op.add_column('streetlight_logs', sa.Column('current_deviation', sa.Float(), nullable=True))
    op.add_column('streetlight_logs', sa.Column('power_trend', sa.Float(), nullable=True))
    op.add_column('streetlight_logs', sa.Column('fault_frequency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streetlight_logs', 'fault_frequency')
    op.drop_column('streetlight_logs', 'power_trend')
    op.drop_column('streetlight_logs', 'current_deviation')
    op.drop_column('streetlight_logs', 'voltage_fluctuation')
    op.drop_column('streetlight_logs', 'operating_hours')
    # ### end Alembic commands ###
