"""add pwm column

Revision ID: de27994391e7
Revises: 0be2a3a925d1
Create Date: 2026-05-08 09:26:40.111636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de27994391e7'
down_revision: Union[str, Sequence[str], None] = '0be2a3a925d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streetlight_logs', sa.Column('pwm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streetlight_logs', 'pwm')
    # ### end Alembic commands ###
