"""init

Revision ID: fde5c2ef6e7d
Revises: 
Create Date: 2026-04-18 01:00:17.056358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde5c2ef6e7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streetlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('model_info', sa.String(), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'faulty', 'maintenance', name='streetlight_status_enum'), server_default='inactive', nullable=False),
    sa.Column('is_on', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streetlights_device_id'), 'streetlights', ['device_id'], unique=True)
    op.create_index(op.f('ix_streetlights_id'), 'streetlights', ['id'], unique=False)
    op.create_index(op.f('ix_streetlights_name'), 'streetlights', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', 'technician', 'viewer', name='userrole'), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('availability', sa.Enum('available', 'busy', 'offline', name='technician_availability_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streetlight_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.Enum('FAULT', name='alert_type_enum'), server_default='FAULT', nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alert_severity_enum'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['streetlight_id'], ['streetlights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('predictive_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streetlight_id', sa.Integer(), nullable=True),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', name='urgency_level_enum'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['streetlight_id'], ['streetlights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictive_alerts_id'), 'predictive_alerts', ['id'], unique=False)
    op.create_table('predictive_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streetlight_id', sa.Integer(), nullable=True),
    sa.Column('failure_probability', sa.Float(), nullable=True),
    sa.Column('predicted_failure_date', sa.DateTime(), nullable=True),
    sa.Column('urgency_level', sa.Enum('low', 'medium', 'high', name='urgency_level_enum'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['streetlight_id'], ['streetlights.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('streetlight_id')
    )
    op.create_index(op.f('ix_predictive_maintenance_id'), 'predictive_maintenance', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_table('streetlight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streetlight_id', sa.Integer(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('power_consumption', sa.Float(), nullable=True),
    sa.Column('light_intensity', sa.Float(), nullable=True),
    sa.Column('is_on', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['streetlight_id'], ['streetlights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streetlight_logs_id'), 'streetlight_logs', ['id'], unique=False)
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predictive_alert_id', sa.Integer(), nullable=True),
    sa.Column('streetlight_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'assigned', 'in_progress', 'completed', name='maintenance_task_status_enum'), server_default='pending', nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='maintenance_task_priority_enum'), server_default='medium', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['predictive_alert_id'], ['predictive_alerts.id'], ),
    sa.ForeignKeyConstraint(['streetlight_id'], ['streetlights.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predictive_alert_id')
    )
    op.create_index(op.f('ix_maintenance_tasks_id'), 'maintenance_tasks', ['id'], unique=False)
    op.create_table('repair_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('predictive_alert_id', sa.Integer(), nullable=True),
    sa.Column('streetlight_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by_type', sa.Enum('admin', 'operator', 'self_assigned', name='assigned_by_type_enum'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'assigned', 'in_progress', 'completed', name='repair_task_status_enum'), server_default='pending', nullable=False),
    sa.Column('source_type', sa.Enum('FAULT', 'PREDICTIVE', name='repair_task_source_type_enum'), server_default='FAULT', nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='repair_task_priority_enum'), server_default='high', nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['predictive_alert_id'], ['predictive_alerts.id'], ),
    sa.ForeignKeyConstraint(['streetlight_id'], ['streetlights.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id'),
    sa.UniqueConstraint('predictive_alert_id')
    )
    op.create_index(op.f('ix_repair_tasks_id'), 'repair_tasks', ['id'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streetlight_id', sa.Integer(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_task_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parts_replaced', sa.String(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='maintenance_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_task_id'], ['maintenance_tasks.id'], ),
    sa.ForeignKeyConstraint(['streetlight_id'], ['streetlights.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('maintenance_task_id')
    )
    op.create_index(op.f('ix_maintenance_logs_id'), 'maintenance_logs', ['id'], unique=False)
    op.create_table('repair_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repair_task_id', sa.Integer(), nullable=False),
    sa.Column('streetlight_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('parts_replaced', sa.String(), nullable=True),
    sa.Column('repair_duration_minutes', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repair_task_id'], ['repair_tasks.id'], ),
    sa.ForeignKeyConstraint(['streetlight_id'], ['streetlights.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repair_task_id')
    )
    op.create_index(op.f('ix_repair_logs_id'), 'repair_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repair_logs_id'), table_name='repair_logs')
    op.drop_table('repair_logs')
    op.drop_index(op.f('ix_maintenance_logs_id'), table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_index(op.f('ix_repair_tasks_id'), table_name='repair_tasks')
    op.drop_table('repair_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_id'), table_name='maintenance_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_index(op.f('ix_streetlight_logs_id'), table_name='streetlight_logs')
    op.drop_table('streetlight_logs')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_predictive_maintenance_id'), table_name='predictive_maintenance')
    op.drop_table('predictive_maintenance')
    op.drop_index(op.f('ix_predictive_alerts_id'), table_name='predictive_alerts')
    op.drop_table('predictive_alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_streetlights_name'), table_name='streetlights')
    op.drop_index(op.f('ix_streetlights_id'), table_name='streetlights')
    op.drop_index(op.f('ix_streetlights_device_id'), table_name='streetlights')
    op.drop_table('streetlights')
    # ### end Alembic commands ###
